services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - "8000:8000"
      - "5173:5173"
    command: sleep infinity
    stdin_open: true
    tty: true

  dtrack-db:
    image: postgres:18-alpine
    environment:
      - POSTGRES_USER=dtrack
      - POSTGRES_PASSWORD=dtrack
      - POSTGRES_DB=dtrack
      - POSTGRES_HOST_AUTH_METHOD=trust
      - LANG=en_US.utf8
      - POSTGRES_INITDB_ARGS=--locale-provider=icu --icu-locale=en-US
    volumes:
      - ./dtrack_db_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dtrack" ]

  dtrack-apiserver:
    image: dependencytrack/apiserver
    ports:
      - "8080:8080"
    environment:
      - ALPINE_DATABASE_MODE=external
      - ALPINE_DATABASE_URL=jdbc:postgresql://dtrack-db:5432/dtrack
      - ALPINE_DATABASE_DRIVER=org.postgresql.Driver
      - ALPINE_DATABASE_USERNAME=dtrack
      - ALPINE_DATABASE_PASSWORD=dtrack
    volumes:
      - ./dtrack_data:/data
      - ./dtrack_tmp:/tmp
    depends_on:
      dtrack-db:
        condition: service_healthy

  dtrack-frontend:
    image: dependencytrack/frontend
    ports:
      - "3000:8080"
    environment:
      - API_BASE_URL=http://localhost:8080
    depends_on:
      - dtrack-apiserver
